### ISSUE TITLE
Spaces break step 2

### ISSUE THREAD

**Issue by kpsf** [forcedotcom/scmt-app#13]
We need to strip spaces from the fields in step 2

**Comment by minjunyang88** [comment]
To add more details to the issue, if you enter extra space before or after the actual value, the authentication won't work.

**Comment by kpsf** [comment]
@minjunyang88 I think we should move this one to the server side. We can strip out whitespace there. Also, it's better for the user experience if we accept little mistakes like this without having to make the user find and remove the spaces.
