### ISSUE TITLE
Grant migration user the R/W permission for the “unassigned” queue

### ISSUE THREAD

**Issue by minjunyang88** [forcedotcom/scmt-app#18]
Ensure that the migration user has R/W permission for the “unassigned” queue.

**Comment by tstachl** [comment]
@minjunyang88 does this not happen during the "Group Member" migration?

**Comment by minjunyang88** [comment]
No. I had to manually assign myself to the "unassigned" queue.

**Comment by tstachl** [comment]
Issue moved to [forcedotcom/scmt-server #44](https://github.com/forcedotcom/scmt-server/issues/44) via [**ZenHub**](https://www.zenhub.com/)
