### ISSUE TITLE
UI issue in calendar picker

### ISSUE THREAD

**Issue by minjunyang88** [forcedotcom/scmt-app#2]
UI issue in calendar picker (using chrome latest version): http://screencast.com/t/uZUc4bfxf1b

**Comment by tstachl** [comment]
@wyattsweet this might be a good issue as a first contribution 😄

**Comment by tstachl** [comment]
![image](https://cloud.githubusercontent.com/assets/286093/23383189/0463fb44-fcfa-11e6-8508-c33d72008238.png)
