### ISSUE TITLE
Remove first company filter option from UI

### ISSUE THREAD

**Issue by minjunyang88** [forcedotcom/scmt-app#3]
Remove company filter option from UI since we don't allow that search logic in Desk for company object.

**Comment by tstachl** [comment]
@minjunyang88 which filter are we talking about here? 
![image](https://cloud.githubusercontent.com/assets/286093/23081553/38686daa-f50a-11e6-9d77-ed444e3724cf.png)

**Comment by minjunyang88** [comment]
Second one.

More details: 
From the paper trail, looks like it's searching for the company ID as unix timestamp, so when I entered this company id: 96977444, the request looks like this in papertrail: https://zzz-minjunyang.desk.com/api/v2/companies/search?q=(created_at:[96977444%20TO%201477603525])&per_page=500&page=1&sort_field=created_at&sort_direction=asc

But if I select ""Migrate All Data"", the request looks like this: https://zzz-minjunyang.desk.com/api/v2/companies/search?q=(created_at:[1%20TO%201477603736])&per_page=500&page=1&sort_field=created_at&sort_direction=asc

That's why regardless which option I chose, it's alway migration all companies.

Side Note: same option is working properly for customer object.

**Comment by tstachl** [comment]
@minjunyang88 do we want to fix it or do we want to remove it? Maybe hide the option for now and fix it later?

**Comment by minjunyang88** [comment]
@tstachl we should just hide it for now because currently Desk API doesn't support this yet. We can add this back in when/if Desk supports this.
