### ISSUE TITLE
UI enhancement - csv file for error logs

### ISSUE THREAD

**Issue by minjunyang88** [forcedotcom/scmt-app#4]
Generate a CSV file of all the error logs on each object with detailed error message

**Comment by tstachl** [comment]
@minjunyang88 can this be achieved by using the monitoring tool SFDC has already built in: 

![image](https://cloud.githubusercontent.com/assets/286093/23185947/1a90059e-f83a-11e6-8bfa-589979a6c9c4.png)

**Comment by minjunyang88** [comment]
So the feedback that I got from customers are those logs are in json format, which is very difficult to analyze. It would be great if there is a downloadable csv file for them to directly look at. Also, it would be nice to include the Desk ID of the migrated record. (From our earlier discussions, this might be difficult to achieve, right?) But just want to put it here for further investigation.
