### ISSUE TITLE
UI enhancement - migration progress

### ISSUE THREAD

**Issue by minjunyang88** [forcedotcom/scmt-app#6]
Customer asked if there was a way to see the progress on the server - maybe it can be exposed somehow? Might clash with ToS of the papertrail heroku add on we're currently using.

**Comment by tstachl** [comment]
@minjunyang88 how would this clash with the Terms of Service of Papertrail? If required we can have someone from legal take a look at it.

**Comment by minjunyang88** [comment]
@tstachl , that was your comment in the quip doc that I copied here: "Might clash with ToS of the papertrail heroku add on we're currently using." Let me know if it's still doable. If not, we can look into other options. FYI -  this is an enhancement request from customers.

**Comment by minjunyang88** [comment]
Closing this issue because I've broken this into different smaller tasks.
