### ISSUE TITLE
Add additional permissions to the permission set.

### ISSUE THREAD

**Issue by tstachl** [forcedotcom/scmt-app#8]
We need to add application, object, field, tab and page permissions to the permission set so it doesn't have to be done by hand after the installation.

**Comment by minjunyang88** [comment]
Mostly resolved. The only thing is after we connect Desk to Salesforce in step 2, new fields will be created. At this point, the app was already installed. Is there a way to workaround it so that user doesn't have manually grant r/w permission for all the contact, account and case custom fields?
